import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { VideoButton } from "components.slint";

export component App inherits Window {
    preferred-width: 640px;
    preferred-height: 512px;
    min-width: 640px;
    min-height: 512px;
    title: "Slint GStreamer Example";
    background: #BBBBBB66;

    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        VideoButton {
            text: self.clicked ? "Pause" : "Play";
        }
    }
}
