import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { VideoWindow, VideoControls } from "video-controls.slint";

export component App inherits Window {
    preferred-width: 640px;
    preferred-height: 480px;
    min-width: 640px;
    min-height: 100px;
    title: "Slint GStreamer Example";
    background: #BBBBBB66;

    VerticalLayout {
        spacing: 5px;
        VideoWindow { }

        VideoControls { }
    }
}
