import { Button } from "std-widgets.slint";
import { Styles } from "styles.slint";
component VideoButton inherits Rectangle {

    in property <string> text;
    out property <bool> clicked: false;

    width: Math.max(content.width + Styles.padding * 2, 100px);
    height: content.height + Styles.padding * 2;
    border-radius: 8px;
    background: Styles.video_gradient;
    border-width: 1px;
    border-color: #24266b;

    content := Text {
        text: text;
        color: #24266b;
        font-weight: 100000;
    }

    TouchArea {
        clicked => {
            clicked = !clicked;
        }
    }
}
