import { Button, ScrollView, ComboBox} from "std-widgets.slint";
import { Styles } from "styles.slint";

component VideoText inherits Text {
    text: "example text";
    font-size: 12px;
    font-weight: 600;
    color: Styles.video_color;
}

component VideoButton inherits Rectangle {

    in property <string> text;
    out property <bool> clicked: false;

    width: Math.max(content.width + Styles.padding * 2, 100px);
    height: content.height + Styles.padding * 2;
    border-radius: 8px;
    background: Styles.video_gradient;
    border-width: ta.has-hover ? 2px : 1px;
    border-color: Styles.video_color;

    content := VideoText {
        text: text;
        font-weight: ta.has-hover ? 1000 : 600;
    }

    ta := TouchArea {
        clicked => {
            clicked = !clicked;
        }
    }
}

component VideoComboBox inherits Window {
    background: transparent;
    ComboBox {
        model: ["first", "second", "third_option"];
        current-value: "first";
    }
}

export component VideoWindow inherits Rectangle {
    min-width: 640px;
    min-height: 360px;
    border-radius: 8px;
    background: transparent;
    border-width: 1px;
    border-color: Styles.video_color;
}

export component VideoControls {
    HorizontalLayout {
        HorizontalLayout {
            alignment: start;
            spacing: 5px;
            play_button := VideoButton {
                text: self.clicked ? "Pause" : "Play";
            }

            screenshot_button := VideoButton {
                text: "Screenshot";
            }
        }

        HorizontalLayout {
            alignment: end;
            spacing: 5px;
            VideoText {
                vertical-alignment: center;
                horizontal-alignment: right;
                text: "Select video source:";
            }

            VideoComboBox { }
        }
    }
}
